environments:
  ENV: "I WAS IN QA"
  SQL_PORT: "I WAS THERE"
  SQL_SERVER: "172.1.2.3"
  DSFDSF_ENCRYPT: "7oqvmBtbDvyvu9y1BLxY"
  SQL_SERVER_PASS_ENCRYPT: "sta2zkJIWKH/"
  ELASTIC_ADDRESS: "https://search-kubernates-xvmidfo7uo7wtw47fxtlo46j7u.us-west-1.es.amazonaws.com"
  ELASTIC_PASSWORD: "Coffe519!"
  ELASTIC_USERNAME: "admin"
  SERVICE_NAME: "trading-alert"
  WHATSAPP_TOKEN: EAAyW0AzZB8ZBsBO0ZBH4djZB7Kc74zfMJDfFqqfZB8ZCqsvqQLqMqGiXDg44ZC3V5vxO0ybrcvZA5SF7o6x1EZCVZC53M6aPZB555j85Wu71xDQFbCyeZBvDr39w8K296blqJlocRYeG2sLyEZCX5ZBJVRrWrm1e2wZAuTXqnxxcSLnGdeZAZByQPhZA4yEpZCu1ZC0aZBpLfzCtJq2JKEHBZBIzHFM74U
